### ISSUE TITLE
Practica 2 Visual Studio UI

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-topicos_a-4bs-idm#1]
Reporte de parctica
[Practica 2 Visual Studio UI.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-topicos_a-4bs-idm/files/14283713/Practica.2.Visual.Studio.UI.pdf)

Integrantes de Equipo:
Rosas Garcia Marco Uriel
Cruz  Cruz Diego
Jimenez Sanchez Irvin

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tienen un 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
